//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace panfilovamv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int id { get; set; }
        public Nullable<int> Service_id { get; set; }
        public string ServiceName { get; set; }
    
        public virtual Reservations Reservations { get; set; }
    }
}
